servo/html5ever

Makefile.in, bench/tokenizer.rs, examples/noop-tree-builder.rs, examples/print-rcdom.rs, examples/print-tree-actions.rs, examples/tokenize.rs, macros/src/match_token.rs, macros/src/named_entities.rs, src/for_c/common.rs, src/lib.rs, src/macros.rs, src/serialize/mod.rs, src/sink/owned_dom.rs, src/sink/rcdom.rs, src/tokenizer/buffer_queue.rs, src/tokenizer/char_ref/data.rs, src/tokenizer/char_ref/mod.rs, src/tokenizer/interface.rs, src/tokenizer/mod.rs, src/tokenizer/states.rs, src/tree_builder/actions.rs, src/tree_builder/interface.rs, src/tree_builder/mod.rs, src/tree_builder/rules.rs, src/tree_builder/types.rs, src/util/smallcharset.rs, src/util/str.rs, tests/tokenizer.rs
(only Servo branch)
No need to merge yet, wait till the rustup finishes.
=> Update to Rust ffc111889e93bcd38222d9d74a70fdc26a78fcb5/rust-0.13.0-dev

examples/noop-tree-builder.rs, examples/print-tree-actions.rs, src/driver.rs, src/sink/owned_dom.rs, src/sink/rcdom.rs, src/tree_builder/actions.rs, src/tree_builder/interface.rs, src/tree_builder/mod.rs, src/tree_builder/rules.rs
=> Use associated types

data/test/ignore, src/tree_builder/rules.rs
I also updated to the latest `html5lib-tests`.
=> Fix two html5lib tests

src/tree_builder/rules.rs
=> Fix token processing when insertion mode is InColumnGroup

src/for_c/common.rs, src/lib.rs, src/macros.rs, src/sink/owned_dom.rs, src/sink/rcdom.rs, src/tokenizer/buffer_queue.rs, src/tokenizer/char_ref/mod.rs, src/tokenizer/mod.rs, src/tree_builder/actions.rs, src/util/smallcharset.rs, src/util/str.rs
A simple warning fix, resolves #67 .
=> Replaced uint with usize and the 'u' type suffix with 'us'.

src/serialize/mod.rs
Fixes https://github.com/servo/html5ever/issues/99
=> Serialize processing instructions

src/serialize/mod.rs
Fixes https://github.com/servo/html5ever/issues/98
=> Add include_root to SerializeOpts

Cargo.toml, Makefile.in, benches/tokenizer.rs, examples/noop-tokenize.rs, examples/print-rcdom.rs, examples/print-tree-actions.rs, examples/tokenize.rs, macros/Cargo.toml, macros/src/lib.rs, macros/src/named_entities.rs, test_util/src/lib.rs, tests/tokenizer.rs, tests/tree_builder.rs
=> Upgrade to rustc 1.0.0-nightly (cfea8ec41 2015-03-10) (built 2015-03-11)

macros/src/lib.rs
=> Upgrade to rustc 1.0.0-dev (68d694156 2015-03-20)

.travis.yml
=> Travis uses stable by default now

.travis.yml
=> Turn on homu notifications.

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/152)
=> Broken link for example fixed

macros/src/pre_expand.rs, tests/tokenizer.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/154)
=> Upgrade to rustc 1.4.0-nightly (e35fd7481 2015-08-17)

macros/Cargo.toml, macros/src/pre_expand.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/166)
=> Upgrade to rustc 1.4.0-nightly (20a8412e0 2015-08-28)

data/test/ignore, src/tree_builder/tag_sets.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/160)
=> Include the foreign integration points in default scope

src/tree_builder/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/165)
=> Do not check if self-closing flag was acknowledged on end tags

data/test/ignore, tests/tree_builder.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/159)
=> Properly parse test cases with trailing whitespace

data/test/ignore, src/tree_builder/actions.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/162)
=> Properly handle U+0000 NULL when dispatching tree construction

data/test/ignore, src/tree_builder/actions.rs, src/tree_builder/rules.expanded.rs, src/tree_builder/rules.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/161)
=> Properly detect unexpected font start tags in foreign content

data/test/ignore, src/tree_builder/rules.expanded.rs, src/tree_builder/rules.rs
Fixes #13.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/169)
=> Implement <isindex>

macros/src/lib.rs, src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/174)
=> Upgrade to rustc 1.5.0-nightly (0418a43fa 2015-09-21)

Cargo.toml, data/test/ignore, src/tree_builder/rules.expanded.rs, src/tree_builder/rules.rs, src/tree_builder/tag_sets.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/172)
=> Implement <rb> and <rtc> parsing rules (closes #157)

Cargo.toml, macros/Cargo.toml, macros/src/pre_expand.rs
r? @Manishearth @metajack @SimonSapin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/175)
=> Upgrade to Rust nightly 20151002

README.md
Closes #171 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/176)
=> Fix version support in README

Cargo.toml, src/lib.rs, src/tree_builder/interface.rs
Part of Part of servo/heapsize#5.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/177)
=> Add `HeapSizeOf` support.

macros/Cargo.toml, macros/src/match_token.rs, macros/src/pre_expand.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/179)
=> Update to rustc 1.6.0-dev (74185aff2 2015-11-05)

Cargo.toml
r? @larsbergstrom
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/180)
=> Bump cargo

Cargo.toml, macros/Cargo.toml, macros/src/pre_expand.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/181)
=> Rustup to rustc 1.6.0-nightly (5b4986fa5 2015-11-08)

Cargo.toml, capi/Cargo.toml, capi/src/lib.rs, capi/src/tokenizer.rs, examples/noop-tree-builder.rs, examples/print-rcdom.rs, examples/print-tree-actions.rs, macros/src/match_token.rs, macros/src/pre_expand.rs, src/lib.rs, src/rcdom.rs, src/serialize/mod.rs, src/tokenizer/mod.rs, src/tree_builder/actions.rs, src/tree_builder/interface.rs, src/tree_builder/mod.rs, src/tree_builder/rules.expanded.rs, src/tree_builder/rules.rs, src/tree_builder/tag_sets.rs, tests/serializer.rs, tests/tokenizer.rs, tests/tree_builder.rs
r? @asajeffrey
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/184)
=> Upgrade string-cache to 0.2.

Cargo.toml, src/lib.rs, src/rcdom.rs
r? @SimonSapin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/187)
=> Switch from crate rc to std::rc now that Weak is stable

Cargo.toml, src/driver.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/190)
=> Fix a stupid bug in BytesParser.

Cargo.toml, scripts/shrink-test-output.py, scripts/travis-build.sh, tests/tokenizer.rs, tests/tree_builder.rs
https://crates.io/crates/rustc-test/
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/189)
=> Use the test crate from crates.io, run tests on stable.

Cargo.toml
The recent change (#193) was a breaking change
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/194)
=> Bump to 0.5

Cargo.toml, src/driver.rs, src/tree_builder/mod.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/196)
=> Allow Servo to use the driver module’s API

Cargo.toml, benches/tokenizer.rs
r? @nox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/202)
=> rustup `cargo bench`

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/207)
=> Bump to 0.5.4

examples/noop-tree-builder.rs, examples/print-tree-actions.rs, src/rcdom.rs, src/tree_builder/interface.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/209)
=> Make get_template_contents take a mutable self argument.

README.md
I had some troubles with doing this and I didn't realize that a minimal example already exists. The first example does too much stuff so it's not very easy to get started.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/212)
=> html2html is a very helpful example for parsing and then serializing html

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/222)
=> Declare actual quote dependency

macros/match_token.rs, src/tree_builder/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/223)
=> Remove unnecessary hack

Cargo.toml, atoms/Cargo.toml, atoms/lib.rs, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/229)
=> Use heapsize_derive

atoms/Cargo.toml, atoms/local_names.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/230)
=> Add more interned strings; bump version.

Cargo.toml, src/driver.rs, src/tokenizer/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/233)
=> Make TokenizerResult as #[must_use]

benches/tokenizer.rs
Found benchmark broken. Simple fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/235)
=> Fix benchmarking after 7a268f3

atoms/Cargo.toml, atoms/local_names.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/236)
=> Add atom allowfullscreen

scripts/travis-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/237)
=> Build benchmark on CI.

Cargo.toml, src/tokenizer/buffer_queue.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/238)
=> Introduce BufferQueue::pop_front

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/239)
=> Bump syn to 0.10

benches/tokenizer.rs, examples/noop-tokenize.rs, examples/noop-tree-builder.rs, examples/print-tree-actions.rs, examples/tokenize.rs, src/rcdom.rs, src/tokenizer/interface.rs, src/tokenizer/mod.rs, src/tree_builder/interface.rs, src/tree_builder/mod.rs, tests/tokenizer.rs
Rebased from #240.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/243)
=> Track current line when parsing

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/244)
=> Use semver-compatible version number.

Cargo.toml, src/tokenizer/mod.rs, src/tree_builder/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/248)
=> Properly call TokenSink::end from Tokenizer::end

examples/noop-tree-builder.rs, examples/print-tree-actions.rs, src/rcdom.rs, src/tree_builder/actions.rs, src/tree_builder/interface.rs, src/tree_builder/mod.rs, src/tree_builder/types.rs
This reverts commit 69f706988f7d8d79c994809f1a1f25bf9499d959 (https://github.com/servo/html5ever/pull/249).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/252)
=> Revert "Implement support for form owner"

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/255)
=> Update syn to 0.11

atoms/Cargo.toml, atoms/local_names.txt
They are needed for https://github.com/servo/servo/pull/15813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/256)
=> Add "contents" and "scroll-position" keywords to local names

Cargo.toml, examples/noop-tree-builder.rs, examples/print-tree-actions.rs, src/rcdom.rs, src/tree_builder/actions.rs, src/tree_builder/interface.rs, src/tree_builder/mod.rs, src/tree_builder/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/259)
=> Implement support for form owner

xml5ever/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/263)
=> Bump xml5ever version.

markup5ever/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/273)
=> Allow heapsize 0.4

html5ever/Cargo.toml, markup5ever/Cargo.toml, xml5ever/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/278)
=> Update to string-cache 0.6

xml5ever/README.md
Without the space in there, this doesn't show up as nicely on GitHub.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/279)
=> Fix section header formatting.

markup5ever/Cargo.toml, markup5ever/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/280)
=> Custom derive is stable

html5ever/Cargo.toml, html5ever/benches/tokenizer.rs, html5ever/tests/tokenizer.rs, html5ever/tests/tree_builder.rs, xml5ever/Cargo.toml, xml5ever/tests/tokenizer.rs, xml5ever/tests/tree_builder.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/285)
=> Update rustc-test to 0.2, fix breakage on Nightly

html5ever/Cargo.toml, markup5ever/Cargo.toml, scripts/travis-build.sh, xml5ever/Cargo.toml, xml5ever/README.md, xml5ever/tests/tree_builder.rs
https://github.com/servo/tendril/pull/33
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/284)
=> "unstable" Cargo features are now no-ops, to be removed.

html5ever/src/driver.rs
=> Remove Parser::from_bytes reference

README.md
=> Add crates.io badge to README.md

markup5ever/Cargo.toml, markup5ever/local_names.txt
This is required for [MicroData API](https://github.com/servo/servo/wiki/Microdata-project)
=> Pull request to add itemscope and itemprop attributes

xml5ever/src/tokenizer/mod.rs, xml5ever/src/tree_builder/mod.rs
I have fixed this warning by removing unused marco and removing mut before for loop
=> Fix warnings in xml5ever #315

markup5ever/Cargo.toml, markup5ever/local_names.txt
* Added attribute names for microdata in local_names.txt
* Updated minor version
=> Added attribute names for microdata

markup5ever/local_names.txt
=> Add picture local name for picture element

html5ever/Cargo.toml, html5ever/build.rs, html5ever/macros/match_token.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/336)
=> Update syn to 0.12 and quote to 0.4

xml5ever/src/tokenizer/mod.rs
=> Fix typo Attribtes -> Attributes

.travis.yml, README.md, xml5ever/examples/README.md
https://github.com/servo/saltfs/pull/906#issuecomment-436313032
=> Remove unneeded webhook notification

html5ever/Cargo.toml, html5ever/LICENSE-APACHE, html5ever/LICENSE-MIT, markup5ever/Cargo.toml, markup5ever/LICENSE-APACHE, markup5ever/LICENSE-MIT, xml5ever/Cargo.toml, xml5ever/LICENSE-APACHE, xml5ever/LICENSE-MIT
=> Add licenses to all crates.

README.md, xml5ever/README.md
I removed one link as I wasn't able to find it on Travis. Is that correct?
=> Update Travis CI URLs

xml5ever/Cargo.toml, xml5ever/tests/tokenizer.rs, xml5ever/tests/tree_builder.rs
=> Move xml5ever tests from rustc-serialize to serde_json

html5ever/Cargo.toml, html5ever/tests/tokenizer.rs
=> Switch html5ever tests from rustc-serialize to serde_json

README.md
I had trouble understanding the README, and this PR should help others read it.  Obviously, this is opinionated so I will be expecting some changes that will be needed 😉
=> Update README wording for readability/grammar

html5ever/examples/arena.rs, html5ever/macros/match_token.rs, html5ever/src/serialize/mod.rs, html5ever/src/tokenizer/char_ref/mod.rs, html5ever/src/tokenizer/mod.rs, markup5ever/build.rs, markup5ever/entities.rs, markup5ever/interface/mod.rs, rcdom/lib.rs, xml5ever/src/serialize/mod.rs, xml5ever/src/tokenizer/char_ref/mod.rs, xml5ever/src/tokenizer/mod.rs, xml5ever/src/tree_builder/mod.rs
This fixes some Clippy warnings. There are more, and more interesting, warnings in the code base and I would be willing to look into fixing all of them. But first I'd like to know if there's interest in this at all and thus I am opening this pull request with a first set of small changes.
=> Fix some clippy warnings

html5ever/macros/match_token.rs, html5ever/src/driver.rs, html5ever/src/serialize/mod.rs, html5ever/src/tokenizer/char_ref/mod.rs, html5ever/src/tokenizer/mod.rs, html5ever/src/tree_builder/mod.rs, markup5ever/build.rs, markup5ever/util/buffer_queue.rs, rcdom/lib.rs, xml5ever/src/driver.rs, xml5ever/src/serialize/mod.rs, xml5ever/src/tokenizer/char_ref/mod.rs, xml5ever/src/tokenizer/mod.rs, xml5ever/src/tokenizer/qname.rs, xml5ever/src/tree_builder/mod.rs
Another wave of changes suggested by Clippy. There are some warnings left, but this is as far as I will get today.
=> Fix clippy warnings

.github/workflows/main.yml, html5ever/Cargo.toml, html5ever/src/tokenizer/mod.rs, xml5ever/Cargo.toml, xml5ever/src/tokenizer/mod.rs
Newer versions of criterion depend on half which uses features unsupported in older versions of Rust.
=> Don't run bench for 1.41.0.

.github/workflows/main.yml
once_cell updated their MSRV, so we must match.
=> update MSRV to 1.56.

html5ever/macros/match_token.rs, markup5ever/build.rs
This pull request fixes two typos.
=> Fix two typos

README.md
Nice to see an update to this crate! Here's a one-liner to update the README example for the new release number.
=> Update README for 0.27

markup5ever/local_names.txt
Appears in https://html.spec.whatwg.org/multipage/embedded-content.html#htmlimageelement, will be reflecting the 2 attributes in a later PR to servo.
=> Add loading and referrerpolicy to local names

xml5ever/README.md
Update Readme and remove some outdated sections.
=> Make some improvements to the xml5ever README

.github/workflows/main.yml, html5ever/Cargo.toml, markup5ever/Cargo.toml
=> Set the README and release html5ever / markup5ever

html5ever/fuzz/.gitignore, xml5ever/fuzz/.gitignore, xml5ever/fuzz/Cargo.toml, xml5ever/fuzz/fuzz_targets/fuzz_document_parse.rs
In correspondence with fuzzing html5ever. This could be integrated into OSS Fuzz.
=> test(fuzz): fuzz xml5ever

html5ever/Cargo.toml, html5ever/benches/html5ever.rs, xml5ever/Cargo.toml, xml5ever/benches/xml5ever.rs
This is https://github.com/servo/html5ever/pull/611 with the patches required to actually build without warnings.
=> Upgrade criterion to 0.6
