servo/html5ever

Makefile.in
macros/src/match_token.rs
macros/src/named_entities.rs
src/sink/common.rs
src/tokenizer/buffer_queue.rs
src/tokenizer/char_ref/mod.rs
src/tokenizer/interface.rs
src/tokenizer/states.rs
src/tree_builder/actions.rs
src/tree_builder/interface.rs
src/tree_builder/mod.rs
src/tree_builder/types.rs
src/util/str.rs
tests/tokenizer.rs
tests/tree_builder.rs

This fixes all build errors I was seeing in the 2015-01-25 Rust nightly build. `make examples check bench` now runs without errors.

Fix the build on 2015-01-25 Rust nightly

---

.travis.yml

This should provide faster build startup times, and will also allow caching between builds if that seems useful. See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

Opt in to container-based Travis CI builds

---

bench/bin.rs
bench/tokenizer.rs
data/test/ignore
examples/html2html.rs
examples/noop-tokenize.rs
examples/noop-tree-builder.rs
examples/print-rcdom.rs
examples/print-tree-actions.rs
examples/tokenize.rs
macros/src/lib.rs
macros/src/named_entities.rs
src/lib.rs
src/serialize/mod.rs
src/sink/owned_dom.rs
src/sink/rcdom.rs
src/tokenizer/char_ref/mod.rs
src/tree_builder/rules.rs
tests/html5ever-external-test.rs
tests/tokenizer.rs
tests/tree_builder.rs
tests/util.rs

r? @Manishearth 
r=me on the commits that aren't mine :)

Rustup and merge some PRs

---

tests/tokenizer.rs

We now wait to split the input until each test actually runs. This means some duplication of work between tests that previously used the same input, but reduces startup overhead by not performing `Vec` copies. This makes running a single test significantly faster without affecting the total time to run all tests.
Before:
```
$ HTML5EVER_SRC_DIR=$(pwd) time -p ./build/html5ever-external-test --help > /dev/null
real         9.75
user         9.64
sys          0.10
$ HTML5EVER_SRC_DIR=$(pwd) time -p ./build/html5ever-external-test > /dev/null
real        17.72
user        60.12
sys          3.72
```
After:
```
$ HTML5EVER_SRC_DIR=$(pwd) time -p ./build/html5ever-external-test --help > /dev/null
real         0.51
user         0.49
sys          0.01
$ HTML5EVER_SRC_DIR=$(pwd) time -p …
```

Speed up html5ever-external-test startup time

---

macros/src/lib.rs

With this PR we are able to run on current nightly (`rustc 1.0.0-nightly (1d00c545e 2015-01-30 19:56:34 +0000)`) with zero warnings

Remove old orphan check

---

.travis.yml
scripts/shrink-test-output.py
scripts/travis-build.sh

Travis CI won't display build logs longer than 10,000 lines. Since we have so many tests, our CI logs get truncated and you can't see the test failures down at the end of the log.
Instead of printing each test on its own line, we now just print out a single character for each test indiciating success (`.`), failure (`F`), or that the test was ignored (`I`). Failing tests are still printed in full at the end of the test run.

Shrink test output in CI

---

src/tree_builder/mod.rs

Fixes https://github.com/servo/html5ever/issues/96, although with quirks_mode being initialized from an option in TreeBuilderOpts, the responsibility lies with the client of the parser to specify a quirks_mode that matches the target document.

Add quirks_mode to TreeBuilderOpts

---

examples/html2html.rs
examples/noop-tokenize.rs
examples/noop-tree-builder.rs
examples/print-rcdom.rs
examples/print-tree-actions.rs
examples/tokenize.rs
macros/src/lib.rs
src/for_c/common.rs
src/lib.rs
src/sink/owned_dom.rs
src/sink/rcdom.rs
src/tokenizer/buffer_queue.rs
src/tokenizer/interface.rs
src/tokenizer/mod.rs
src/tree_builder/actions.rs
src/tree_builder/interface.rs
src/tree_builder/mod.rs
src/tree_builder/rules.rs
src/util/smallcharset.rs
test_util/src/lib.rs
tests/tokenizer.rs
tests/tree_builder.rs

r? @Manishearth 
The semi-tricky things here are:
* switching from `ContravariantLifetime` to `PhantomData`,
* `unsafe impl Send for Token`, to work around rust-lang/rust#22629

Upgrade to rustc 1.0.0-dev (2b01a37ec 2015-02-21) (built 2015-02-23)

---

src/serialize/mod.rs
src/sink/owned_dom.rs
src/sink/rcdom.rs

In https://github.com/servo/servo/pull/5029, @jdm [requested](https://critic.hoppipolla.co.uk/showcomment?chain=10737) an enum rather than bool for indicating whether to serialize a whole node, or only its children. For consistency, I pushed that suggestion all the way down through html5ever, and it looks like this.

Use enum rather than bool for controlling serialize

---

examples/tokenize.rs
macros/src/lib.rs
src/for_c/common.rs
src/for_c/tokenizer.rs
src/serialize/mod.rs
src/tokenizer/mod.rs
tests/tokenizer.rs
tests/tree_builder.rs

Rustup
rustc 1.0.0-nightly (d17d6e7f1 2015-04-02) (built 2015-04-03)
Minor note: make for_c doesn't work. Not sure why.

Rust upgrade to rustc 1.0.0-nightly (d17d6e7f1 2015-04-02)

---

Cargo.toml
Makefile.in
macros/src/lib.rs
macros/src/match_token.rs
src/tokenizer/mod.rs
tests/tokenizer.rs
tests/tree_builder.rs

Also disable doctests because of https://github.com/rust-lang/cargo/issues/1512
Note that there weren’t any doctest to run anyway.
r? @kmcallister

Upgrade to rustc 1.0.0-nightly (6790b0e51 2015-04-11) (built 2015-04-12)

---

src/sink/owned_dom.rs

Fixes a build warning in rustc nightly.  Move the warning to a doc comment instead. r? @kmcallister

Remove deprecated `unstable` attribute.

---

README.md
STRUCTURE.md
scripts/travis-build.sh

@chris-morgan, is that all the things?
Fixes #148.

Fix dom_sink docs

---

examples/noop-tree-builder.rs
examples/print-tree-actions.rs
src/rcdom.rs
src/tree_builder/interface.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/155)

Improve add_attrs_if_missing()

---

examples/noop-tree-builder.rs
examples/print-rcdom.rs
examples/print-tree-actions.rs
src/rcdom.rs
src/tree_builder/actions.rs
src/tree_builder/interface.rs
src/tree_builder/rules.expanded.rs
src/tree_builder/rules.rs
tests/tree_builder.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/153)

Implement <template>

---

data/test/ignore
tests/tree_builder.rs

Use the expectations' fields script-on and script-off to run the tests with their scripting flag set appropriately.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/158)

Fix <noscript> tests

---

tests/tokenizer.rs
tests/tree_builder.rs

Something change in rustc and the #[start] trick doesn’t run anymore.
This runs a test harness nested in another. It’s not pretty, but it works.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/168)

Run tree builder and tokenizer tests again.

---

src/driver.rs

`tokenize_to` was at some point changed to move the `sink` value instead of taking a mut ref, but the inline rustdoc example was not updated, causing lots of confusion
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/170)

Update inline tokenize example

---

Cargo.toml
build.rs

… in Cargo features.
The 'codegen' feature is only useful when working on that file, dependency don’t need it. But they might still want NonZero/unsafe_no_drop_flag optimizations when on Rust Nightly.
This will reduce breaking of dependent crates when libsyntax changes.
r? @nox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/182)

Separate tree_builder/rules.rs code generation from unstable optimizations

---

src/tokenizer/mod.rs

Fixes #109, I'm really not sure whether I'm doing the right thing.
r? @kmcallister 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/183)

Add function to change tokenizer state to Plaintext

---

Cargo.toml
capi/Cargo.toml

People stuck on 0.1.5 and lower with a Cargo.lock file get a compile error
about using the core_intrinsics feature.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/185)

Bump Tendril to 0.1.6

---

data/test/ignore
src/rcdom.rs
src/tree_builder/actions.rs
src/tree_builder/interface.rs
src/tree_builder/tag_sets.rs

r? @nox
#119 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/186)

Add is_mathml_annotation_xml_integration_point method

---

Cargo.toml
build.rs
capi/Cargo.toml
capi/src/lib.rs
capi/src/tokenizer.rs
examples/html2html.rs
examples/noop-tokenize.rs
examples/noop-tree-builder.rs
examples/print-rcdom.rs
examples/print-tree-actions.rs
examples/tokenize.rs
scripts/travis-build.sh
src/driver.rs
src/lib.rs
src/rcdom.rs
src/tree_builder/interface.rs
tests/serializer.rs
tests/tree_builder.rs

This depends on https://github.com/servo/tendril/pull/23.
This also adds an API to parse from bytes, which is part of https://github.com/servo/html5ever/issues/18.
r? @nox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/188)

Rewrite the high-level API (driver module) to use TendrilSink

---

src/tree_builder/interface.rs
src/tree_builder/mod.rs

This allows Handles to be moved while tracing.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/193)

Use references to handles while tracing

---

Cargo.toml
src/driver.rs

This is intended to avoid issues when there's a parser-blocking script in the first 1024 bytes. See also #198.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/199)

Limit the encoding detection to 3 bytes for now.

---

src/serialize/mod.rs
tests/serializer.rs

As said here [1], the line break after the doctype is undesirable.
[1] https://github.com/servo/servo/pull/10604#issuecomment-209942021
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/206)

Remove blank line after serializing doctype

---

Cargo.toml
src/lib.rs
src/macros.rs

Crate time is deprecated; switch to `std::time`
Cheers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/213)

Use std::time instead of deprecated crate time

---

tests/foreach_html5lib_test/mod.rs

I propose the change because I had this problem when I did cargo test:
```
[....]$ RUST_BACKTRACE=1 cargo test
Running target/debug/html5ever-ebbb862bf0664388
running 20 tests
....................
test result: ok. 20 passed; 0 failed; 0 ignored; 0 measured
Running target/debug/serializer-bd6e4b6794d0e313
running 40 tests
........................................
test result: ok. 40 passed; 0 failed; 0 ignored; 0 measured
Running target/debug/tokenizer-9fee19ffe67616b5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:788
stack backtrace:
1:        0x10f9e54bb - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
2:        0x10f9e775a - …
```

Fixed too sure .unwrap in tokenizer.rs

---

Cargo.toml
macros/Cargo.toml
macros/src/lib.rs
macros/src/match_token.rs
macros/src/pre_expand.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/218)

Update to latest libsyntax

---

Cargo.toml

0.5.5 was yanked because the change to get_template_contents was a breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/221)

Bump to 0.6

---

Cargo.toml
src/tokenizer/mod.rs
src/tokenizer/states.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/224)

Properly encode the states for CDATA

---

Cargo.toml
examples/noop-tokenize.rs
examples/print-rcdom.rs
examples/tokenize.rs
src/driver.rs
src/lib.rs
src/tokenizer/buffer_queue.rs
src/tokenizer/char_ref/mod.rs
src/tokenizer/interface.rs
src/tokenizer/mod.rs
src/tokenizer/states.rs
src/tree_builder/actions.rs
src/tree_builder/mod.rs
src/tree_builder/rules.rs
tests/tokenizer.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/226)

Make tokenizer not own the input stream

---

benches/tokenizer.rs

Was curious about project benchmarks and noticed it was broken. A quick bisect revealed it was recently broken in 7fec1da. Thankfully there was examples of testing that needed to be updated which correlated directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/227)

fix benchmarking broken by  "Make tokenizer not own the input stream"

---

Cargo.toml
examples/noop-tokenize.rs
examples/tokenize.rs
src/driver.rs
src/tokenizer/interface.rs
src/tokenizer/mod.rs
src/tree_builder/actions.rs
src/tree_builder/interface.rs
src/tree_builder/mod.rs
src/tree_builder/rules.rs
src/tree_builder/types.rs
tests/tokenizer.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/231)

Suspend the whole tokenizer and tree builder on </script>

---

atoms/Cargo.toml
atoms/local_names.txt

I closed my previous PR for this because I wasn't sure it was necessary, but it looks like it is.
Used for subresource integrity checks which I'm currently implementing in Servo to close https://github.com/servo/servo/issues/14523
Ref:
https://w3c.github.io/webappsec-subresource-integrity/
https://html.spec.whatwg.org/multipage/#dom-script-integrity
https://html.spec.whatwg.org/multipage/#dom-link-integrity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/242)

Add "integrity" attribute

---

benches/tokenizer.rs
examples/noop-tokenize.rs
examples/tokenize.rs
src/tokenizer/buffer_queue.rs
src/tokenizer/mod.rs
tests/tokenizer.rs

There was an `#![allow(unused_imports)]` in `src/tokenizer/mod.rs` which looks useless. removed it and other unused imports. Also silenced some warnings in tests/examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/250)

Silence warnings and clean up unused imports

---

examples/noop-tree-builder.rs
examples/print-tree-actions.rs
src/rcdom.rs
src/tree_builder/actions.rs
src/tree_builder/interface.rs
src/tree_builder/mod.rs
src/tree_builder/types.rs

This is rebased version of #137. Fixed merge conflicts, updated to current codebase and addressed some comments. But there are still some todo's needs to be addressed. Servo side of this changes is currently WIP. Opening this for early feedbacks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/249)

Implement support for form owner

---

Cargo.toml
atoms/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/251)

Update string_cache to 0.4

---

atoms/Cargo.toml
atoms/local_names.txt

This reverts PR #256 / commit 6089ea41ad7acae12913d5c8b85864969da8fe5f.
Turns out these atoms are needed in `servo_atoms::Atom`, not `LocalName`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/257)

Revert "Add "contents" and "scroll-position" keywords to local names"

---

src/tokenizer/interface.rs
tests/tokenizer.rs

Token contains StrTendril, which is not Send because it contains a shared reference to a `Cell<usize>` for reference-counting.
Refactor test harness to not need Send.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/253)

Remove incorrect `unsafe impl Send for Token { }`

---

xml5ever/src/serialize/mod.rs

This should fix https://github.com/servo/servo/issues/16213.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/262)

Mark rust code block as regular text in docs.

---

Cargo.toml
atoms/Cargo.toml
xml5ever/CHANGELOG.md
xml5ever/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/264)

Update string-cache in html5ever-atoms.

---

src/driver.rs
xml5ever/src/driver.rs

`s/recieve/receive/g`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/267)

Minor spelling/typo fix

---

html5ever/Cargo.toml
html5ever/examples/html2html.rs
html5ever/examples/print-rcdom.rs
html5ever/src/driver.rs
html5ever/src/lib.rs
html5ever/src/tokenizer/mod.rs
html5ever/src/tree_builder/mod.rs
html5ever/tests/serializer.rs
html5ever/tests/tokenizer.rs
html5ever/tests/tree_builder.rs
markup5ever/Cargo.toml
markup5ever/lib.rs
xml5ever/Cargo.toml
xml5ever/examples/hello_xml.rs
xml5ever/src/driver.rs
xml5ever/src/lib.rs
xml5ever/src/tokenizer/mod.rs
xml5ever/src/tree_builder/mod.rs
xml5ever/tests/tokenizer.rs

It cannot be the future API for handling `<meta charset>` since it does not support interrupting for scripts.
Update Tendril to a version that doesn’t depend on rust-encoding (unless a Cargo feature is enabled).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/272)

Remove broken BytesParser

---

markup5ever/interface/mod.rs

The documentation for `QualName` uses fenced code blocks (the ones that start with three backticks) incorrectly, so that the fence and the `ignore` directive ends up included in the documentation text.
Fenced code blocks must be separated from the preceding paragraph by a blank line.
This also adds some punctuation and tries to demangle some grammar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/html5ever/283)

Fix doc formatting for markup5ever::interface::QualName.

---

html5ever/src/serialize/mod.rs
html5ever/tests/serializer.rs

This prevents panics if `end_elem` or `parent` is called with an empty stack by fabricating a new default ElemInfo.
Normally, this will never happen with valid html, but in the event that someone needs to serialize a token stream representing a malformed tree, they can now do so.
Fixes #292

Don't bail on empty Serializer stack

---

html5ever/examples/noop-tree-builder.rs
html5ever/examples/print-tree-actions.rs
html5ever/src/tree_builder/mod.rs
html5ever/src/tree_builder/types.rs
markup5ever/interface/tree_builder.rs
markup5ever/rcdom.rs

The use of `same_tree` and `has_parent_node` meant that the TreeBuilder needed access to the DOM state to carry out its tasks.

TreeBuilder no longer relies on `same_tree` and `has_parent_node`

---

html5ever/src/serialize/mod.rs
html5ever/tests/serializer.rs
markup5ever/rcdom.rs
markup5ever/serialize.rs
xml5ever/src/serialize/mod.rs

This is necessary so that these nodes exist on the stack when we
serialize the children nodes and may need the parent for context.
Addresses servo/servo#14975
---
Opening this PR for feedback/review
~~This does work and solves the above bug. I'm not sure if this is the best implementation, as there's a bit of duplicated code. I thought about adding a boolean flag to `start_elem` that would determine whether the writes should be performed. But then I thought maybe when not writing, it's best not to call a function returning `io::Result<()>`?~~
Also not 100% sure if the xml implementation is the right thing to do
Anyway, please let me know of any improvements/changes to make. Thanks :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

change type ChildrenOnly to ChildrenOnly(Option<QualName>)

---

html5ever/Cargo.toml
html5ever/examples/arena.rs
html5ever/examples/noop-tree-builder.rs
html5ever/examples/print-tree-actions.rs
html5ever/src/tree_builder/mod.rs
markup5ever/Cargo.toml
markup5ever/interface/tree_builder.rs
markup5ever/rcdom.rs
xml5ever/Cargo.toml

fixes #303 
Continued from https://github.com/servo/html5ever/pull/308

Removed has_parent_node and same_tree methods from TreeSink trait

---

xml5ever/Cargo.toml
xml5ever/src/tree_builder/mod.rs

This addresses the problem from https://github.com/servo/servo/issues/19087. Non-script empty tags go through the `append_tag` code path which does not pop anything from the namespace stack. Empty script tags go through insert_tag/close_tag instead, which does pop an element from the namespace stack.

Reset namespace stack when processing an empty script tag

---

markup5ever/build.rs
markup5ever/data/mod.rs
markup5ever/lib.rs
markup5ever/rcdom.rs
markup5ever/serialize.rs
markup5ever/util/buffer_queue.rs
markup5ever/util/smallcharset.rs

I'm just trying to learn how this lib works, and I'm looking at source to work it out. Hopefully if I doc as I go, others that come after me will benefit :)

Assorted documentation

---

html5ever/Cargo.toml
markup5ever/Cargo.toml
markup5ever/interface/mod.rs
markup5ever/interface/tree_builder.rs
markup5ever/lib.rs
xml5ever/Cargo.toml

Since heapsize isn't used anymore and that string_cache removed its heapsize feature, I removed the feature as a whole meaning that this is a breaking change for h5e and m5e.

Update string_cache to 0.7

---

html5ever/src/tree_builder/mod.rs

As mentioned in #219, `stop_parsing` was assumed to be useless. It still triggers in my project, hence considered removing it.
Hopefully this PR is okay, despite already being assigned to @nox. I simply encountered it a few days ago and decided to make the move, as this issue seems to be there for a while, I preferred to do it myself than bothering anyone for such a small fix : )
Not sure if `"FIXME: </script> not fully implemented"` can be removed as well, if so, just inform me and I will change that as well!

Removed warn-log `stop_parsing not implemented, full speed ahead!`

---

html5ever/Cargo.toml
html5ever/benches/tokenizer.rs
html5ever/tests/tokenizer.rs
html5ever/tests/tree_builder.rs
xml5ever/Cargo.toml
xml5ever/tests/tokenizer.rs
xml5ever/tests/tree_builder.rs

Version 0.2 of the crates.io package `rustc_test` uses `test` as its rustc crate name, shadowing the `test` crate from the standard library. This made us subject to breaking changes to its private APIs.

Update to rustc-test 0.3, unbreak tests on nightly-2018-02-25

---

Cargo.toml

It's pretty surprising when tests and dev builds can't be debugged. Debugging information was disabled in 1223b23 (2015-3-31) because of rust-lang/rust#23110, which was closed 2016-7-14. It should be okay to turn it back on now.

Enable debugging information in dev and test builds.

---

markup5ever/build.rs
markup5ever/interface/mod.rs
markup5ever/interface/tree_builder.rs
markup5ever/rcdom.rs

I recently submitted a PR to add documentation. This PR adds some more.
Note it won't merge as-is because it relies on PR [#199 in servo/string-cache].
[#199 in servo/string-cache]: https://github.com/servo/string-cache/pull/199

Add more documentation

---

html5ever/src/tree_builder/mod.rs
html5ever/src/util/str.rs

`to_escaped_string` is somewhat expensive because it allocates twice and iterates over each char individually to escape it. Furthermore, `TreeBuilder::step` produces a lot of `debug_step` messages. So, we use `log_enabled!` to not escape any strings unless debug messages are being printed.

Use log_enabled! to avoid calling to_escaped_string

---

markup5ever/Cargo.toml
markup5ever/local_names.txt

Add `kind` and `srclang` to the list of `local_names`. They are needed
by the HTMLTrackElement.

Add names used by the HTMLTrackElement

---

html5ever/src/serialize/mod.rs

This allows 3rd party crates to customize the output without duplicating all the serialization logic. I'm using it myself to pretty print transformed html, where I don't care that the added whitespace changes the meaning of the document.

Expose HtmlSerializer for customizing output

---

html5ever/Cargo.toml
html5ever/examples/print-rcdom.rs
html5ever/tests/serializer.rs
html5ever/tests/tree_builder.rs
markup5ever/Cargo.toml
markup5ever/lib.rs
markup5ever/rcdom.rs
xml5ever/Cargo.toml
xml5ever/examples/xml_tree_printer.rs

Serialize rcdom iteratively

---

html5ever/Cargo.toml
markup5ever/Cargo.toml
markup5ever/rcdom.rs
xml5ever/Cargo.toml

Since #372 there is a private field in Node that prevents constructing them manually. If we want to support that, we need to expose the constructor.

Expose public Node constructor.

---

html5ever/Cargo.toml
markup5ever/Cargo.toml
markup5ever/rcdom.rs
xml5ever/Cargo.toml

This is a better solution for the problem solved by 8bf65ef61daf612a3b4d7e6007fde7297d6210eb which doesn't require destroying all nodes when the RcDom is dropped. Fixes #383.

Ensure all RcDom nodes drop children iteratively

---

markup5ever/local_names.txt

`property` can exist as an attribute name in `meta` tags like `<meta property="og:title" content="Title" />`

Add property to local_names

---

Cargo.toml
html5ever/Cargo.toml
html5ever/examples/html2html.rs
html5ever/examples/print-rcdom.rs
html5ever/src/driver.rs
html5ever/src/tree_builder/mod.rs
html5ever/tests/serializer.rs
html5ever/tests/tree_builder.rs
markup5ever/Cargo.toml
markup5ever/interface/tree_builder.rs
markup5ever/lib.rs
rcdom/Cargo.toml
rcdom/README.md
rcdom/lib.rs
xml5ever/Cargo.toml
xml5ever/examples/hello_xml.rs
xml5ever/examples/xml_tree_printer.rs
xml5ever/src/driver.rs
xml5ever/tests/tree_builder.rs

The RcDom implementation was never intended as anything more than a test-only implementation. This work extracts it into a separate crate that contains a README that lays out what sort of support and maintenance guarantees anybody choosing to rely on it can expect (read: none).
Fixes #385.

Extract RcDom into its own crate with no support guarantees

---

html5ever/src/tree_builder/tag_sets.rs
html5ever/src/util/str.rs
xml5ever/src/tree_builder/mod.rs
xml5ever/src/util/mod.rs

```rust
error[E0659]: `matches` is ambiguous (glob import vs any other name from outer scope during import/macro resolution)
--> html5ever/src/tree_builder/tag_sets.rs:109:5
|
109 |     matches!(
|     ^^^^^^^ ambiguous name
|
= note: `matches` could refer to a macro from prelude
note: `matches` could also refer to the macro imported here
--> html5ever/src/tree_builder/tag_sets.rs:13:5
|
13  | use mac::*;
|     ^^^^^^
= help: consider adding an explicit import of `matches` to disambiguate
= help: or use `self::matches` to refer to this macro unambiguously
error: aborting due to 2 previous errors
```

Fix ambiguity of glob import with `matches!` now in the standard library

---

README.md

Changing the link from `.../html5ever/examples/...` to `.../rcdom/examples/...`

Updating outdated link in the README

---

markup5ever/local_names.txt

Most of these are for HTML elements; "parse" is for xinclude, which at least one SVG library uses as explained in https://github.com/servo/html5ever/issues/369#issuecomment-573078302

Add local names mentioned in #369

---

html5ever/fuzz/.gitignore
html5ever/fuzz/Cargo.toml
html5ever/fuzz/fuzz_targets/fuzz_document_parse.rs

This is work that will be coordinated with integration of the [OSS-Fuzz](https://github.com/google/oss-fuzz) infrastructure, which allows continuous fuzzing for the project. 
I had a short talk with @jdm about this. 
Once this has been merged I will set up the project on the OSS-Fuzz side and then we should be up and running :)!

Added a document parse fuzzer

---

rcdom/lib.rs
rcdom/tests/html-driver.rs
rcdom/tests/html-tree-builder.rs

This is an extension of the work from https://github.com/servo/html5ever/pull/384.

Drop template contents interatively.

---

rcdom/lib.rs

This cuts the time taken for one pathological fuzzing testcase from 9s to 5.5s.

Use a VecDeque for serialization to avoid inefficient array operations.

---

markup5ever/local_names.txt

This is in CSS3, which is kind of required for SVG2, which I'm slowly getting at in librsvg :smiley:

Add "line-height"

---

html5ever/fuzz/fuzz_targets/fuzz_document_parse.rs

This shouldn't lose much coverage, since we didn't perform any validation of the actual output bytes. By creating a black hole for serialization, we avoid the risk of OOMing when serializing arbitrary fuzzer inputs.

Don't store serialized data in memory when fuzzing.

---

html5ever/examples/print-tree-actions.rs
rcdom/examples/print-rcdom.rs
rcdom/examples/xml_tree_printer.rs
xml5ever/examples/README.md

The `escape_default` method was stabilized in Rust 1.34 [1] and workarounds
are no longer needed.
[1] https://doc.rust-lang.org/std/primitive.str.html#method.escape_default

Remove escape_default workarounds

---

html5ever/src/tree_builder/mod.rs
html5ever/src/tree_builder/rules.rs
html5ever/src/util/str.rs

The custom `is_ascii_whitespace` function was added before the standard
library version was added. The standard library `is_ascii_whitespace` method
was added in Rust 1.24 [1]. The implementations are nearly identical except
for the order of the matched characters, which should not matter.
[1] https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii_whitespace

Use std `is_ascii_whitespace`

---

xml5ever/Cargo.toml
xml5ever/src/lib.rs

time 0.1 has known security issues, and it's not really necessary to use time crate anymore for getting precise instants as std::time::Instant::now [has the same implementation as precise_time_ns on popular platforms](https://stackoverflow.com/a/55619763).

Remove time dependency

---

html5ever/src/tokenizer/mod.rs
xml5ever/src/tokenizer/mod.rs

This removes warnings about "trailing semicolon in macro used in expression position".
See https://github.com/rust-lang/rust/issues/79813.

Remove trailing semicolons from macro bodies

---

html5ever/src/tokenizer/mod.rs

html5ever doesn't currently use trace!() anywhere. This patch
downgrades a few of the noisiest debug!() calls to use trace!()
instead.
This seems like a more reasonable log level for a tokenizer.
This makes configuring env_logger to debug other code easier
(RUST_LOG=debug rather than RUST_LOG=html5ever=info,debug), and
makes working with minimal wasm log frameworks like console_log
nicer (the console_log crate doesn't have a way to set different
levels for different log prefixes).
There is a single debug statement in html5ever/src/tokenizer/mod.rs that I've not changed:
debug!("processing EOF in state {:?}", self.state);
I didn't change this to trace, because I notice this log line anywhere in my logs. If you want me to change this too, then I can.
I'm also happy to close this PR, if you …

use trace!() in tokenizer, to reduce log spam

---

.github/workflows/main.yml
html5ever/Cargo.toml
markup5ever/Cargo.toml
rcdom/Cargo.toml
xml5ever/Cargo.toml

Since the pfh map is exposed in markup5ever's public API, we need to release a new major version when the phf dependency is updated.

Update markup5ever major version and all other crates.

---

.github/workflows/main.yml

Updates the `actions/checkout` action used in the GitHub Actions workflow to its newest version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.0.2
> - Add input `set-safe-directory`
>
> ## v3.0.1
> - Fixed an issue where checkout failed to run in container jobs due to the new git setting `safe.directory`
> - Bumped various npm package versions
>
> ## v3.0.0
>
> - Update to node 16
As far as I can tell this should all be backwards compatible, so I do not expect any breakage.

Update actions/checkout in GitHub Actions to v3

---

markup5ever/util/buffer_queue.rs
rcdom/lib.rs
xml5ever/src/serialize/mod.rs
xml5ever/src/tokenizer/mod.rs
xml5ever/src/tree_builder/mod.rs

Clippy generated several warnings about how "this expression creates a reference which is immediately dereferenced by the compiler" [1]. I've removed the references since they don't do anything.
There are also some rustfmt changes that my editor automatically made.
[1] https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

Remove needless borrows

---

rcdom/examples/print-rcdom.rs

As a Rust noob, I _think_ this is the simplest way to stop string allocations for the indentation, but I'd love to know if there is a better way to do this. I believe `.collect::<String>()` in the old code was causing a String allocation, and I think a simplified version that I almost went with (`print!("{}", " ".repeat(indent));`) would [do the same thing](https://doc.rust-lang.org/std/primitive.str.html#method.repeat), so I think this PR should be sufficient.
/cc @jdm

Stop allocating string for rcdom example

---

html5ever/src/serialize/mod.rs

This adds the default value for `scripting_enabled` in the documentation.

Complete Default documentation of `SerializeOpts`

---

html5ever/build.rs

hello, the following patch allows compilation to work for haiku.
example build run is shown below:
```
> uname -a
Haiku shredder 1 hrev56154 Jun  3 2022 18:56:03 x86_64 x86_64 Haiku
> rustc --version
rustc 1.60.0 (2e3e23e17 2022-04-05)
> cargo build
Compiling cfg-if v1.0.0
Compiling libc v0.2.112
Compiling getrandom v0.1.16
Compiling siphasher v0.3.7
Compiling ppv-lite86 v0.2.16
Compiling proc-macro2 v1.0.36
Compiling unicode-xid v0.2.2
Compiling parking_lot_core v0.8.5
Compiling smallvec v1.8.0
Compiling new_debug_unreachable v1.0.4
Compiling serde v1.0.133
Compiling scopeguard v1.1.0
Compiling mac v0.1.1
Compiling syn v1.0.85
Compiling log v0.4.14
Compiling lazy_static v1.4.0
Compiling utf-8 v0.7.6
Compiling precomputed-hash v0.1.1
Compiling instant v0.1.12
Compiling phf_shared v0.10.0 …
```

compile fix for haiku

---

html5ever/src/tokenizer/mod.rs
rcdom/custom-html5lib-tokenizer-tests/regression.test

This fixes a bug in the tokenizer where the tag name was included in a bogus comment after an appropriate end tag.
For example, this:
```html
<style></style ><!a>
```
is incorrectly parsed as the following:
```html
<style></style>
```
instead of the expected:
```html
<style></style>
```
For this bug to trigger, the end tag needs to be parsed in one of the raw text states (RCDATA, RAWTEXT, or Script data) and have whitespace or a slash after the tag name. I don't know how the contents of the temporary buffer end up inside the comment, but clearing the temporary buffer when exiting the `RawEndTagName` state seems to be enough to fix it.

Fix parsing of bogus comments after end tags

---

html5ever/src/tokenizer/mod.rs

While searching for potential points in the code to which I could contribute I came across this FIXME comment 
which seemed like an easy-win:
```rust
// FIXME: linear time search, do we care?
```
(line 511 in `html5ever/src/tokenizer/mod.rs`)
I Tries using a HashSet for the attributes names so the search's complexity would be O(1) instead of O(n), as 
can be seen in [this commit](https://github.com/servo/html5ever/commit/df17e5b87ce43f5a3206bf21c4b21ed78276874e)
and once I ran some benchmarks on multiple websites (by [modifying the noop-tokenizer example](https://hatebin.com/bndkyirfnm)) I realized I only made things worst, the Parsing process took a tiny bit longer than before. This is probably because of the overhead within maintaining a HashSet of the attributes names, and because most …

Remove redundant FIXME comment

---

.github/workflows/main.yml
html5ever/Cargo.toml
html5ever/src/lib.rs
html5ever/src/tokenizer/char_ref/mod.rs
html5ever/src/util/str.rs
markup5ever/Cargo.toml
rcdom/Cargo.toml
xml5ever/Cargo.toml

Not completely sure if changes from #460 should be considered semver-incompatible? It looks like they add new states but then also the `states` module has these comments:
```
//! This is public for use by the tokenizer tests.  Other library
//! users should not have to care about this.
```
So maybe it doesn't matter?
As far as I can tell other changes are not semver-incompatible.

html5ever: prepare 0.26.1 release

---

html5ever/examples/noop-tokenize.rs
html5ever/examples/noop-tree-builder.rs
html5ever/examples/print-tree-actions.rs
html5ever/examples/tokenize.rs
html5ever/src/serialize/mod.rs
html5ever/src/tree_builder/mod.rs
rcdom/examples/hello_xml.rs
rcdom/examples/html2html.rs
rcdom/examples/print-rcdom.rs
rcdom/examples/xml_tree_printer.rs
rcdom/lib.rs
rcdom/tests/html-tokenizer.rs
rcdom/tests/html-tree-builder.rs

Not completely sure why I missed these [the last time around](https://github.com/servo/html5ever/pull/517), probably because they're in examples?

Remove more unnecessary imports

---

html5ever/Cargo.toml
xml5ever/Cargo.toml

This avoids compilation failing for the benchmark targets.

Make criterion a regular dev-dependency

---

.github/workflows/main.yml

The check is from the time when the MSRV was included in the build matrix.

Remove unnecessary version check from the benchmark build step

---

html5ever/src/tokenizer/interface.rs

Bare URLs are not automatically turned into clickable links.

docs: Fix bare URL in rustdoc

---

.github/workflows/main.yml
rcdom/Cargo.toml
rcdom/tests/html-tokenizer.rs
rcdom/tests/html-tree-builder.rs
rcdom/tests/util/runner.rs
rcdom/tests/xml-tokenizer.rs
rcdom/tests/xml-tree-builder.rs
xml5ever/Cargo.toml

The `rustc-test` crate v0.3.1 depends on rustc-serialize v0.3 which is unmaintained and unfortunately no longer compiles under rust 1.77.1.
Remove this crate in favour of a trivial test runner. This drops many nice features of the rustc test runner like parallelization, colour output, per-subtest command line selection support, and output capture on failure. On the other hand, it reduces the maintenance surface and unbreaks the build.
Resolves #526

Remove rustc-test dependency

---

html5ever/Cargo.toml
html5ever/src/tokenizer/mod.rs
rcdom/tests/xml-tokenizer.rs
xml5ever/Cargo.toml
xml5ever/src/tokenizer/mod.rs

From the lint job:
```
error: methods `get_bool` and `get_list` are never used
--> rcdom/tests/xml-tokenizer.rs:147:8
|
143 | trait JsonExt: Sized {
|       ------- methods in this trait
...
147 |     fn get_bool(&self) -> bool;
|        ^^^^^^^^
148 |     fn get_obj(&self) -> &Map<String, Self>;
149 |     fn get_list(&self) -> &Vec<Self>;
|        ^^^^^^^^
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
```
From the nightly CI:
```
error: unexpected `cfg` condition name: `trace_tokenizer`
--> html5ever/src/tokenizer/mod.rs:625:11
|
625 | #[cfg(not(trace_tokenizer))]
|
= help: consider using a Cargo feature instead
= help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
[lints.rust]
unexpected_cfgs …
```

Fix errors in CI.

---

markup5ever/local_names.txt

While playing around the `<link>` element in Servo, I noticed that the "as" IDL attribute doesn't play nice because the name is not included in `local_names`.
https://html.spec.whatwg.org/multipage/semantics.html#dom-link-as

fix: add 'as' to local_names

---

html5ever/benches/html5ever.rs
html5ever/examples/noop-tokenize.rs
html5ever/examples/tokenize.rs
html5ever/src/driver.rs
html5ever/src/tokenizer/char_ref/mod.rs
html5ever/src/tokenizer/mod.rs
markup5ever/util/buffer_queue.rs
rcdom/tests/html-serializer.rs
rcdom/tests/html-tokenizer.rs
rcdom/tests/xml-tokenizer.rs
xml5ever/benches/xml5ever.rs
xml5ever/examples/simple_xml_tokenizer.rs
xml5ever/examples/xml_tokenizer.rs
xml5ever/src/driver.rs
xml5ever/src/tokenizer/char_ref/mod.rs
xml5ever/src/tokenizer/mod.rs

Part of https://github.com/servo/servo/issues/32454
from @jdm [comment](https://github.com/servo/servo/issues/32454#issuecomment-2158242638)

Convert BufferQueue to use Interior Mutability

---

html5ever/examples/arena.rs
html5ever/examples/noop-tree-builder.rs
html5ever/examples/print-tree-actions.rs
html5ever/src/tree_builder/mod.rs
html5ever/src/tree_builder/rules.rs
html5ever/src/tree_builder/types.rs
markup5ever/interface/mod.rs
markup5ever/interface/tree_builder.rs
markup5ever/serialize.rs
rcdom/lib.rs
rcdom/tests/html-tree-sink.rs
xml5ever/src/tree_builder/mod.rs

Fixes #552
This allows this type to be owned or contain data protected by a RefCell or Mutex. It can also simply be `ExpandedName` - the type which was previously the return type of `TreeSink::elem_name`.
I have not yet had a chance to test this, but I believe this ought to fix my issue.

Make return type of `TreeSink::elem_name` an associated type.

---

html5ever/Cargo.toml
markup5ever/Cargo.toml
rcdom/Cargo.toml
xml5ever/Cargo.toml

@jdm Any chance of a new release with the changes in [#553](https://github.com/servo/html5ever/pull/553)?

Bump version numbers (html:0.29, xml:0.20, markup:0.14)

---

rcdom/Cargo.toml
rcdom/tests/html-tokenizer.rs
rcdom/tests/html-tree-builder.rs
rcdom/tests/util/runner.rs
rcdom/tests/xml-tokenizer.rs
rcdom/tests/xml-tree-builder.rs

https://github.com/servo/html5ever/pull/528 regressed the DX
significantly, add a lighter and more maintained test harness to get
basic functionality like "run one test" back.

Add libtest-mimic

---

html5ever/benches/html5ever.rs
html5ever/examples/print-tree-actions.rs
html5ever/examples/tokenize.rs
html5ever/macros/match_token.rs
html5ever/src/serialize/mod.rs
html5ever/src/tokenizer/mod.rs
html5ever/src/tree_builder/mod.rs
html5ever/src/util/str.rs
markup5ever/build.rs
rcdom/examples/hello_xml.rs
rcdom/examples/print-rcdom.rs
rcdom/examples/xml_tree_printer.rs
rcdom/tests/html-tokenizer.rs
rcdom/tests/html-tree-builder.rs
rcdom/tests/xml-tokenizer.rs
rcdom/tests/xml-tree-builder.rs
xml5ever/benches/xml5ever.rs
xml5ever/examples/simple_xml_tokenizer.rs
xml5ever/examples/xml_tokenizer.rs
xml5ever/src/serialize/mod.rs
xml5ever/src/tokenizer/mod.rs
xml5ever/src/tree_builder/mod.rs

style: simplify some statements for readability

---

html5ever/Cargo.toml

crates.io seems wholly unconvinced that [`html5ever` is an "html parser" when sorting by 'Relevance'](https://crates.io/search?q=html%20parser). Hopefully this will clear up the confusion for it

docs(html5ever): Add `Cargo.toml` keywords

---

.github/workflows/main.yml
Cargo.toml
html5ever/Cargo.toml
markup5ever/Cargo.toml
rcdom/tests/html-tokenizer.rs
xml5ever/Cargo.toml
xml5ever/src/tokenizer/mod.rs

#568 added new methods to a public trait, but they have default implementations so this can be treated as a minor version bump (https://doc.rust-lang.org/cargo/reference/semver.html#trait-new-default-item).

Publish html5ever 0.29.1 and markup5ever 0.14.1.

---

.gitignore

Adds VSCode and Idea RustRover folder to .gitignore

nit: VS Code and Idea exclusions

---

markup5ever/Cargo.toml

Bumping version of string cache codegen to `0.5.4` to stabilize `generated_rs` atom's write order.
I assume `html5ever` and `xml5ever` will auto-update their dependencies and pickup latest `markup5ever`.
Fix #573

Bump `string_cache_codegen` to `0.5.4`

---

html5ever/Cargo.toml
markup5ever/Cargo.toml
rcdom/Cargo.toml
xml5ever/Cargo.toml

https://github.com/servo/html5ever/pull/578 made a breaking change to markup5ever: [any change to trait item signatures](https://doc.rust-lang.org/cargo/reference/semver.html#trait-item-signature)

Publish html5ever 0.29.2 and markup5ever 0.15.0

---

xml5ever/Cargo.toml

Extend to https://github.com/servo/html5ever/pull/581
Bump xml5ever version to 0.20.1

Bump xml5ever version to 0.20.1

---

rcdom/tests/xml-driver.rs
xml5ever/src/serialize/mod.rs
xml5ever/src/tree_builder/mod.rs

Fixes #569
This is @jdm's `xmlns-attrs` branch posted in #569, plus an update to `xml5lib-tests` by @Ygg01 (https://github.com/servo/html5ever/issues/569#issuecomment-2661417199)

Store xml namespace attributes for later serialization

---

html5ever/src/driver.rs
html5ever/src/tokenizer/mod.rs
html5ever/src/tree_builder/mod.rs
markup5ever/interface/mod.rs
markup5ever/interface/tree_builder.rs
markup5ever/lib.rs
rcdom/tests/xml-tokenizer.rs
xml5ever/benches/xml5ever.rs
xml5ever/examples/simple_xml_tokenizer.rs
xml5ever/examples/xml_tokenizer.rs
xml5ever/src/driver.rs
xml5ever/src/tokenizer/interface.rs
xml5ever/src/tokenizer/mod.rs
xml5ever/src/tree_builder/mod.rs
xml5ever/src/tree_builder/types.rs

This is the same approach used by html5ever, which will hopefully allow unifying their API a bit as part of the effort for encoding support.
This is a breaking change. The TreeSink::complete_script method (among other things) is removed.

xml5ever: Bubble parser blocking scripts to the caller instead of the TreeSink

---

html5ever/Cargo.toml
markup5ever/Cargo.toml
rcdom/Cargo.toml
xml5ever/Cargo.toml

This should have been done as part of https://github.com/servo/html5ever/pull/591. I forgot that servo depends on the crates.io version of html5ever, not the git repository. So to upgrade in servo we need to release new versions of all three crates.
All three crates have received breaking changes since the last PR.
cc @mrobinson since I think you have permission to create new releases?

Bump xml5ever, markup5ever and html5ever versions

---

html5ever/src/tree_builder/mod.rs
html5ever/src/tree_builder/rules.rs
html5ever/src/tree_builder/types.rs
match_token/src/lib.rs

Currently the tokenizer and treebuilder in html5ever import all variants of  commonly used enums:
```rust
enum Token {
FooToken,
BarToken
}
use Token::*;
fn main() {
let x = FooToken;
}
```
This is not really idiomatic rust. I've never seen any other codebase do this, and it is not the style we use in servo either.
This change removes the imports and instead uses the `Token::Foo` notation, renaming the variants where appropriate. 
This is a breaking change, because the `PushFlag` import was public (*even though it really shouldn't have been, I suspect that's another common problem in html5ever*).

Don't import enum variants into the global namespace in html5ever

---

rcdom/tests/xml-driver.rs
xml5ever/Cargo.toml
xml5ever/src/serialize/mod.rs
xml5ever/src/tree_builder/mod.rs

#586 introduced new test failures in Servo around XML serialization. I shouldn't have merged it without verifying the changes there first, so I'm backing it out until further investigation is possible.

Revert "Store xml namespace attributes for later serialization"

---

html5ever/src/tokenizer/mod.rs
html5ever/src/tree_builder/mod.rs
html5ever/src/tree_builder/rules.rs
rcdom/Cargo.toml
rcdom/examples/hello_xml.rs
rcdom/examples/html2html.rs
rcdom/examples/xml_tree_printer.rs
rcdom/tests/html-tokenizer.rs
rcdom/tests/html-tree-builder.rs
rcdom/tests/xml-tokenizer.rs
rcdom/tests/xml-tree-builder.rs

* Fix some clippy errors
* Add documentation to a few methods
* initialize logger for rcdom examples, so they are more useful for debugging
These are changes that I did while looking a bit into https://github.com/servo/html5ever/issues/588, they're not particularly not important but it feels silly to not commit them.

Initialize logger for rcdom examples, cleanup html5ever a bit

---

xml5ever/src/tree_builder/mod.rs
xml5ever/src/tree_builder/types.rs

This is mostly the same as https://github.com/servo/html5ever/pull/593 but for xml5ever.

Don't import xml5ever enums into the global namespace

---

html5ever/src/tokenizer/char_ref/mod.rs
html5ever/src/tree_builder/mod.rs
html5ever/src/tree_builder/rules.rs

In modern rust this macro can almost always easily be replaced by let-else expressions.
Some uses inside other macros remain, those are not as easy to remove.

Remove all direct uses of unwrap_or_return! in html5ever

---

html5ever/src/macros.rs
html5ever/src/tokenizer/mod.rs
html5ever/src/tree_builder/mod.rs

This change is the first step in gradually removing the `go!` macro that is currently used to implement the tokenizer-DSL.
When this macro was first introduced it might have made sense to have it - some quality-of-life rust syntax did not exist back then.
But I think it's not necessary anymore and I'm certain that it's possible to remove the DSL without compromising on performance or readability (like [this](https://github.com/simonwuelker/Stormlicht/blob/863ec3b841424629a8356b8786f60e305d95a877/crates/web/src/html/tokenization/tokenizer.rs#L1341-L1361)).

Trigger errors without macros, remove `unwrap_or_else!` and `go_match!`

---

markup5ever/Cargo.toml

I believe this should allow us to release the split-out `web_atoms` crate in a non-breaking release.
Steps:
- Merge this PR
- Publish `web_atoms` 0.1
- Publish `markup5ever` 0.16.1
- Update and merge Servo version bump (with lint fix) https://github.com/servo/servo/pull/36542/files

Bump markup5ever to `0.16.1`

---

web_atoms/Cargo.toml

Only the category slugs listed at https://crates.io/category_slugs are allowed. I had to remove this one and publish with `--allow-dirty` to perform the initial publish of web_atoms.

Remove unsupported category.

---

web_atoms/local_names.txt

Required for https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-textcontent
and https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-innertext
Part of servo/servo#36258

Add `innerText` and `textContent` as localname

---

web_atoms/Cargo.toml

This includes the changes from #608.

Publish web_atoms 0.1.1.

---

html5ever/src/tokenizer/mod.rs
markup5ever/util/buffer_queue.rs

The data state is where the HTML tokenizer spends most of it's time. It is also very simple - all it does is scan the input stream for the next character in a set. This can easily be optimized with SIMD instructions. The algorithm I used is described in https://lemire.me/blog/2024/06/08/scan-html-faster-with-simd-instructions-chrome-edition/.
This change significantly speeds up the tokenizer. Both `lipsum.html` and `lipsum.zh.html` see improvements of 70-80%, which is not suprising since they never leave the data state.
Very small inputs regress slightly. There is also a performance regression of ~5% for malicious input that consists only of tags (the `strong.html` benchmark). In that case the SIMD instructions are overkill because the target character (`<`) is always the first one in the …

Add a fast path for the data state using SSE2 instructions

---

html5ever/src/serialize/mod.rs
html5ever/src/tokenizer/mod.rs
html5ever/src/tree_builder/mod.rs
markup5ever/interface/mod.rs
markup5ever/interface/tree_builder.rs
markup5ever/util/buffer_queue.rs
xml5ever/src/tokenizer/mod.rs
xml5ever/src/tokenizer/qname.rs
xml5ever/src/tree_builder/mod.rs

This fixes the CI for https://github.com/servo/html5ever/pull/614.

Fix clippy errors on nightly channel

---

web_atoms/Cargo.toml

Apologies for the PR spam, I forgot to bump the crate version in https://github.com/servo/html5ever/pull/614.

Release web-atoms 0.1.3

---

rcdom/tests/xml-tokenizer.rs
xml5ever/examples/simple_xml_tokenizer.rs
xml5ever/examples/xml_tokenizer.rs
xml5ever/src/tokenizer/interface.rs
xml5ever/src/tokenizer/mod.rs
xml5ever/src/tree_builder/mod.rs
xml5ever/src/tree_builder/types.rs

This continues the work from https://github.com/servo/html5ever/pull/597

Don't re-export xml5ever `Token` variants

---

html5ever/Cargo.toml
rcdom/Cargo.toml

This version includes https://github.com/servo/html5ever/pull/593, which is a breaking change.

Publish html5ever 0.32.0.

---

html5ever/Cargo.toml
html5ever/src/driver.rs
html5ever/src/tree_builder/mod.rs
rcdom/Cargo.toml
rcdom/tests/html-serializer.rs
rcdom/tests/html-tree-builder.rs

Companion PR for https://github.com/servo/servo/pull/37704. Refer to that PR for a description of the change.
Fixes https://github.com/servo/html5ever/issues/579
This is a breaking change.

Determine the initial state for fragment parsing using the scripting flag of the context element

---

README.md
html5ever/Cargo.toml
html5ever/src/tree_builder/mod.rs
html5ever/src/tree_builder/rules.rs
markup5ever/interface/tree_builder.rs
rcdom/Cargo.toml

The string is unused, so this is just a pointless allocation. This change returns a `bool` indicating the operations success instead.
Additionally, pass a reference to the elements attributes. The callee can decide whether they need ownership of the vector or not (servo doesn't).

Don't return a string from `TreeSink::attach_declarative_shadow_root`

---

html5ever/benches/html5ever.rs
markup5ever/interface/mod.rs
markup5ever/util/buffer_queue.rs

This clone operation should not be counted towards the benchmark time. When the benchmark was written criterion did not support per-iteration setup, but now it does using `Bencher::iter_batched`. Using this method reduces the benchmark time by 9% in `lipsum.html`.
Additionally, the way html5ever was used inside the benchmarks was wrong if there were `<script>` elements in the input. 
To fully tokenize input in html5ever, you need to spin on the `Tokenizer::feed` method until it returns `Done`.
None of our benchmarks contain any script elements, but it's better to fix it anyways.

Don't clone input buffer inside html5ever benchmark loop

---

html5ever/src/tokenizer/char_ref/mod.rs
html5ever/src/tokenizer/mod.rs

Not a breaking change because these are not publicly exported.

Don't import Status/State enum variants into the global namespace.

---

rcdom/tests/html-tokenizer.rs

The current test runner assumes that each input chunk can be tokenized without interruptions. This is not true when `<script>` tags are involved and it is not how the tokenizer is meant to be used. Instead, we should spin until `tokenizer.feed` returns `TokenizerResult::Done`.

Wait until input is fully tokenized in tokenizer tests

---

xml5ever/src/tokenizer/states.rs

Fixes https://github.com/servo/html5ever/issues/648.

Document `xml5ever/tokenizer/states.rs`

---

match_token/LICENSE-APACHE
match_token/LICENSE-MIT

I came across this issue when preparing package updates for html5ever et al. for Fedora.
It looks like when match_token was split off into a separate crate (in https://github.com/servo/html5ever/commit/feced062a9119d6f8279cf9d002f9a93926a8ca4), adding the Apache-2.0 and MIT license texts was missed.
On the other hand, this was done correctly when when the web_atoms crate was split off (in https://github.com/servo/html5ever/commit/0292f3fddfe2926aa06c9b67c5ed312a67047ec3) so the fact that the license texts are missing from the match_token crate looks like a simple accidental omission.

match_token: add missing license texts

---

xml5ever/src/tokenizer/mod.rs
xml5ever/src/tokenizer/states.rs

Servo previously needed this state, but doesn't anymore.
This is a breaking change, but all repositories on GitHub using `Quiescent` (that I could find) were html5ever forks.
Fixes https://github.com/servo/html5ever/issues/649

Remove `XmlState::Quiescent`

---

tendril/src/tendril.rs

- Fixes https://github.com/servo/tendril/issues/30

Impl `PartialEq<str>` for `Tendril<ASCII>` and `Tendril<UTF8>`

---

.github/workflows/main.yml

Aim here is:
- To increase parallelism (benchmarks run in parallel with build/test)
- Make it clearer which part has failed if there is a failure
- Stop tests from only running after benchmarks
Update: running the `tendril`/`futf` benchmarks in "quick mode" brings total CI time down to ~1m from ~6m (and doesn't seem to affect benchmark results)

CI: Run benchmarks separately to tests
